version: '3.8'

services:
  image-search-app:
    build: .
    ports:
      - "8080:8080"  # Flask app
      - "5000:5000"  # MRISA API
    volumes:
      - ./app/static/uploads:/app/static/uploads
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - MRISA_API_URL=http://localhost:5000/search