apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-search-app-uploads-pvc
  namespace: image-search-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi